using Npgsql;
using PgDbBackup.Tests.Fixtures;
using Xunit;

namespace PgDbBackup.Tests;

/// <summary>
/// Identity column coverage. Verifies the implicit identity sequence
/// preserves its current value across restore so the first INSERT on
/// the restored DB does not collide with an existing row.
/// </summary>
public sealed class IdentityColumnsValueTests
{
    private readonly PgContainerFixture _pg;

    public IdentityColumnsValueTests(PgContainerFixture pg) => _pg = pg;

    [Fact]
    public async Task Always_Identity_SequenceValue_Preserved_Across_Restore()
    {
        await using var src = await _pg.CreateFreshDbWithExtensionAsync();
        await src.ExecAsync(
            "CREATE TABLE id_always(" +
            "  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, " +
            "  name text NOT NULL);" +
            "INSERT INTO id_always(name) " +
            "  SELECT 'r' || g FROM generate_series(1, 50) g;");

        var full = Helpers.BackupPath("id_always");
        await src.BackupFullAsync(full, compress: true);
        await src.CloseAsync();

        var target = "id_always_" + Guid.NewGuid().ToString("N")[..8];
        try
        {
            await RestoreAsync(target, full);
            await using var r = await _pg.ConnectToAsync(target);

            // Existing row count survives.
            await using (var cmd = r.CreateCommand())
            {
                cmd.CommandText = "SELECT count(*), max(id) FROM id_always";
                await using var rdr = await cmd.ExecuteReaderAsync(
                    TestContext.Current.CancellationToken);
                Assert.True(await rdr.ReadAsync(TestContext.Current.CancellationToken));
                Assert.Equal(50L, rdr.GetInt64(0));
                Assert.Equal(50L, rdr.GetInt64(1));
            }

            // First INSERT post-restore must NOT collide with id=50.
            await using (var cmd = r.CreateCommand())
            {
                cmd.CommandText =
                    "INSERT INTO id_always(name) VALUES ('post') RETURNING id";
                var v = (long)(await cmd.ExecuteScalarAsync(
                    TestContext.Current.CancellationToken))!;
                Assert.True(v > 50,
                    $"Expected identity to advance past 50, got {v}");
            }
        }
        finally
        {
            try { await _pg.DropDbAsync(target); } catch { }
        }
    }

    [Fact]
    public async Task ByDefault_Identity_With_Manual_Override_Survives_Restore()
    {
        await using var src = await _pg.CreateFreshDbWithExtensionAsync();
        await src.ExecAsync(
            "CREATE TABLE id_default(" +
            "  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "  v int);" +
            // Sequence starts at 1, but we OVERRIDE with id=1000 so the
            // sequence still points at 1. Restore must preserve the
            // sequence value AND the inserted row.
            "INSERT INTO id_default(id, v) VALUES (1000, 99);" +
            // Bump the sequence past the manual id so future inserts work.
            "SELECT setval(" +
            "  pg_get_serial_sequence('id_default', 'id'), 1000, true);");

        var full = Helpers.BackupPath("id_default");
        await src.BackupFullAsync(full, compress: true);
        await src.CloseAsync();

        var target = "id_default_" + Guid.NewGuid().ToString("N")[..8];
        try
        {
            await RestoreAsync(target, full);
            await using var r = await _pg.ConnectToAsync(target);

            await using (var cmd = r.CreateCommand())
            {
                cmd.CommandText =
                    "INSERT INTO id_default(v) VALUES (100) RETURNING id";
                var v = (int)(await cmd.ExecuteScalarAsync(
                    TestContext.Current.CancellationToken))!;
                Assert.True(v >= 1001,
                    $"Expected identity > 1000, got {v}");
            }
        }
        finally
        {
            try { await _pg.DropDbAsync(target); } catch { }
        }
    }

    private async Task RestoreAsync(string target, string file)
    {
        await using var admin = await _pg.AdminAsync();
        await using var cmd = admin.CreateCommand();
        cmd.CommandText =
            "SELECT dbbackup.pg_dbrestore(@files::text[], target_db := @tgt)";
        cmd.Parameters.AddWithValue("files", new[] { file });
        cmd.Parameters.AddWithValue("tgt", target);
        cmd.CommandTimeout = 300;
        await cmd.ExecuteNonQueryAsync(TestContext.Current.CancellationToken);
        NpgsqlConnection.ClearAllPools();
    }
}
